#!/bin/bash
#$ -P bf528
#$ -cwd
#$ -pe omp 16
source /etc/bashrc
module load subread/1.6.2
#$ -o run_fcounts.stdout
#$ -e run_fcounts.stderr
GTF=/project/bf528/project_3/reference/rn4_refGene_20180308.gtf 
for file in /projectnb/bf528/users/frazzled/project_3/data_curator/STAR_results/*.bam
do 
f=$(basename "$file")
f=${f:0:10}
echo $f
OUT=/projectnb/bf528/users/frazzled/project_3/programmer/fCounts$f.txt
featureCounts -T 16 -a $GTF -o $OUT $file
done;
